export const blogPosts = [
  {
    id: "first-ivf-consultation-narasaraopet",
    title: "What to Expect at Your First IVF Consultation",
    slug: "first-ivf-consultation-narasaraopet",
    excerpt: "A calm, practical guide for couples preparing for a fertility consultation in Narasaraopet.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80", // PLACEHOLDER — replace via admin panel in Phase 2
    category: "Fertility",
    readTime: "4 min read",
    date: "2026-07-10",
    tags: ["IVF centre Narasaraopet", "infertility treatment Andhra Pradesh"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Patient Education",
    content: [
      "Your first fertility consultation is a conversation, not a commitment to treatment. The doctor will review your medical history, prior reports, and goals.",
      "Couples are encouraged to bring previous scans, lab reports, prescriptions, and any fertility treatment documents.",
      "The care team should explain possible investigations, timelines, and next steps in clear language before a treatment plan is selected."
    ],
    published: true,
  },
  {
    id: "fertility-testing-before-treatment",
    title: "Why Fertility Testing Comes Before Treatment",
    slug: "fertility-testing-before-treatment-narasaraopet",
    excerpt: "Understand how scans, lab reports, and partner screening guide a clearer fertility plan.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80", // PLACEHOLDER - replace via admin panel in Phase 2
    category: "Fertility Testing",
    readTime: "5 min read",
    date: "2026-07-10",
    tags: ["fertility testing Narasaraopet"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Patient Education",
    content: [
      "Fertility testing helps identify ovulation, tubal, uterine, semen, hormonal, infectious, and genetic factors before a treatment plan is selected.",
      "Couples should bring prior scans, prescriptions, semen reports, hormone panels, and any previous IVF or IUI documents to the consultation."
    ],
    published: true,
  },  // Seeding the 12 real titles as drafts
  {
    id: "understanding-infertility",
    title: "Understanding Infertility: Causes and Solutions",
    slug: "understanding-infertility",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Infertility"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "ivf-journey-guide",
    title: "The IVF Journey: Step-by-Step Guide for Aspiring Parents",
    slug: "ivf-journey-guide",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["IVF"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "boosting-fertility-naturally",
    title: "Boosting Fertility Naturally: Diet, Lifestyle, and Wellness",
    slug: "boosting-fertility-naturally",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Fertility", "Wellness"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "exploring-iui-vs-ivf",
    title: "Exploring IUI vs. IVF: Which Treatment is Right for You?",
    slug: "exploring-iui-vs-ivf",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["IVF", "IUI"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "emotional-wellbeing-treatment",
    title: "Emotional Well-Being During Infertility Treatments",
    slug: "emotional-wellbeing-treatment",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Mental Health"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "male-infertility-myths-causes",
    title: "Male Infertility: Myths, Causes, and Treatment Options",
    slug: "male-infertility-myths-causes",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Male Infertility"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "understanding-age-and-fertility",
    title: "Understanding Age and Fertility: What You Need to Know",
    slug: "understanding-age-and-fertility",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Age", "Fertility"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "success-stories-journeys",
    title: "Success Stories: Inspiring Journeys from Sreya IVF Centre",
    slug: "success-stories-journeys",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Stories",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Success Stories"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "common-misconceptions-infertility",
    title: "Common Misconceptions About Infertility Treatments",
    slug: "common-misconceptions-infertility",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Fertility",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Infertility Myths"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "advanced-technology-fertility",
    title: "The Role of Advanced Technology in Fertility Treatment",
    slug: "advanced-technology-fertility",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Technology",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Technology"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "mental-health-fertility",
    title: "The Role of Mental Health in Fertility",
    slug: "mental-health-fertility",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Mental Health",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Mental Health"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  },
  {
    id: "innovations-freezing",
    title: "Innovations in Egg and Sperm Freezing",
    slug: "innovations-freezing",
    excerpt: "Draft content - awaiting final review.",
    coverImageUrl: "https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1400&q=80",
    category: "Technology",
    readTime: "1 min read",
    date: "2026-07-10",
    tags: ["Fertility Preservation"],
    author: "Sreya Hospitals Care Team",
    authorTitle: "Draft Article",
    content: ["TODO: write full article"],
    published: false,
  }
];
